#!/bin/bash
#
# Startup script for FEAT
#
# feat: Flumotion Asynchronous Autonomous Agent Toolkit
#
# chkconfig: - 80 20
#
# source function library
. /etc/rc.d/init.d/functions
PROG="feat-service"
USER="feat"
CONF="/etc/feat/feat.ini"
SYSCONFIG="/etc/sysconfig/feat"

FEAT_DEBUG="*:3"

if [ -f "$SYSCONFIG" ]; then
    source "$SYSCONFIG"
fi

RETVAL=0

start() {
    echo -n $"Starting $PROG: "
    daemon --user $USER $PROG -D -C $CONF start 2> /dev/null
    RETVAL=$?
    let $RETVAL && echo "failed..." || echo "done!"
}

stop() {
    echo -n $"Stopping $PROG: "
    $PROG -C $CONF stop
    let $RETVAL && echo "failed..." || echo "done!"
}

status() {
    $PROG -C $CONF status
    RETVAL=$?
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  status)
        status
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit $RETVAL
